Merging lots of development
dsa110/dsa110-calib pull request #13
Opened 2021-12-09 21:54 UTC by caseyjlaw

2021-12-10 16:02 UTC, danasimard requested changes

2021-12-10 16:02 UTC, danasimard commented on dsacalib/hdf5_io.py
> +
Moved into sefds.py

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> +            if vals is not None:
Assertion line 453 above means that only one check needs to be done here

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> +            if vals is not None:
Again, we only need to check that vals is not None here

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> +                if vals is not None:
Again, we only need to check that vals is not None here

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> +            if vals is not None:
Again, we only need to check that vals is not None here

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> +                if vals is not None:
Again, we only need to check that vals is not None here

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> -def write_beamformer_weights(msname, calname, caltime, antennas, outdir,
This function is moved to weights.py

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> -def write_beamformer_solutions(
This is also moved to weights.py

2021-12-10 16:02 UTC, danasimard commented on dsacalib/ms_io.py
> -
Moved to weights.py

2021-12-10 16:02 UTC, danasimard commented on dsacalib/routines.py
> -def _gauss_offset(xvals, amp, mean, sigma, offset):
Moved to sefds.py

2021-12-10 16:02 UTC, danasimard commented on dsacalib/sefds.py
> +    return vis
This is more appropriate in ms_io.py instead of sefds.py

2021-12-10 16:02 UTC, danasimard commented on dsacalib/sefds.py
> +    return vis
With that move, it also makes sense to allow the datacolumn to be specified

2021-12-10 16:02 UTC, danasimard commented on services/calibration_service.py
> -    return beamformer_names, latest_solns
Replaced by look-up of all recent solutions (not just ones at the current dec) in weights.py

2021-12-10 16:02 UTC, danasimard commented on services/calibration_service.py
> -
Moved to weights.py

2021-12-10 20:45 UTC, caseyjlaw commented on dsacalib/sefds.py
> +    return vis
Would you like to push a commit to the development branch for this move?

2021-12-10 20:47 UTC, danasimard commented on dsacalib/sefds.py
> +    return vis
Yes, I'll do that.

2021-12-10 20:48 UTC, caseyjlaw commented on dsacalib/ms_io.py
> +            if vals is not None:
I think it would be safer for you to you push a commit to this branch with these changes.

2021-12-10 20:49 UTC, danasimard commented
@caseyjlaw I think all of these changes are mine, so I'll make them and push to development.  I also noticed that there are some changes I made to the real-time ms creation on ds/dev that aren't captured in development. I'm testing those and will push those to development as well.

2021-12-12 17:45 UTC, danasimard commented on dsacalib/sefds.py
> +    return vis
I've made these changes.

2021-12-12 18:00 UTC, danasimard approved these changes

2021-12-12 18:00 UTC, danasimard commented on dsacalib/weights.py
> +    refant_ind = ANTENNAS.tolist().index(int(REFANTS[0]))
Even though this is the antenna that the gains are solved against, I wonder if it is better to use a T antenna here.  The refant is typically an outrigger, but what matters for the search sensitivity is having good T antenna beamformer weights.

2021-12-12 18:01 UTC, merged